name: iOS AI App Builder

on:
  push:
    branches:
      - build-*

jobs:
  build:
    name: Build iOS app from AI-generated code
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect scheme and project
        id: detect
        run: |
          scheme=$(xcodebuild -list -json | jq -r '.project.schemes[0]')
          project=$(ls *.xcodeproj | head -1)
          echo "scheme=$scheme" >> $GITHUB_OUTPUT
          echo "project=$project" >> $GITHUB_OUTPUT

      - name: Build app
        run: |
          xcodebuild -scheme "${{ steps.detect.outputs.scheme }}" \
                     -project "${{ steps.detect.outputs.project }}" \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     build

      - name: Archive build
        run: |
          zip -r app.zip ${{ steps.detect.outputs.project }} template

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: app.zip
