name: Build iOS App

on:
  push:
    branches:
      - build-*

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Build app
        run: |
          xcodebuild -scheme template -project template.xcodeproj -sdk iphonesimulator build

      - name: Archive app
        run: zip -r app.zip template.xcodeproj template

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: app.zip
